/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FUNCTION = 5;
  /** RegularExpression Id. */
  int TIPOINTEGER = 6;
  /** RegularExpression Id. */
  int TIPOSTRING = 7;
  /** RegularExpression Id. */
  int TIPOREAL = 8;
  /** RegularExpression Id. */
  int IS = 9;
  /** RegularExpression Id. */
  int VAR = 10;
  /** RegularExpression Id. */
  int ENDVAR = 11;
  /** RegularExpression Id. */
  int CODE = 12;
  /** RegularExpression Id. */
  int ENDCODE = 13;
  /** RegularExpression Id. */
  int RETURN = 14;
  /** RegularExpression Id. */
  int INTEGER = 15;
  /** RegularExpression Id. */
  int REAL = 16;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int DIGITO = 19;
  /** RegularExpression Id. */
  int DOISPONTOS = 20;
  /** RegularExpression Id. */
  int VIRGULA = 21;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 22;
  /** RegularExpression Id. */
  int PARENTESE1 = 23;
  /** RegularExpression Id. */
  int PARENTESE2 = 24;
  /** RegularExpression Id. */
  int PLUS = 25;
  /** RegularExpression Id. */
  int SUB = 26;
  /** RegularExpression Id. */
  int MULT = 27;
  /** RegularExpression Id. */
  int DIV = 28;
  /** RegularExpression Id. */
  int MOD = 29;
  /** RegularExpression Id. */
  int ASPAS = 30;
  /** RegularExpression Id. */
  int PONTO = 31;
  /** RegularExpression Id. */
  int QUOTE = 32;
  /** RegularExpression Id. */
  int ENDQUOTE = 34;
  /** RegularExpression Id. */
  int CHAR = 35;
  /** RegularExpression Id. */
  int CNTRL_ESC = 36;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;
  /** Lexical state. */
  int ESC_STATE = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"function\"",
    "\"integer\"",
    "\"string\"",
    "\"real\"",
    "\"is\"",
    "\"var\"",
    "\"endvar\"",
    "\"code\"",
    "\"endcode\"",
    "\"return\"",
    "<INTEGER>",
    "<REAL>",
    "<IDENTIFICADOR>",
    "<LETTER>",
    "<DIGITO>",
    "\":\"",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"\\\"\"",
    "\".\"",
    "\"\\\'\"",
    "\"\\\\\"",
    "<ENDQUOTE>",
    "<CHAR>",
    "<CNTRL_ESC>",
  };

}
